# Generated by Django 3.2.12 on 2022-04-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_url',
            new_name='url',
        ),
    ]
