# Generated by Django 3.2.12 on 2022-04-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220419_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
